### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by vickystickz**
Added **Code Contributions** message

### CODE REVIEW

**Review by petya-kangalova — APPROVED** [review]
Looks good, approving.

**Comment by petya-kangalova** [comment]
@kshitijrajsharma  can you check and merge?

**Comment by kshitijrajsharma** [comment]
Contributing needs more information , For eg : There should be steps about understanding the license , navigating to readme , follow the ethical guidelines , coding standards , proper branching name and PR methods ! We can work on it future , Merging this PR for now to start with

**Comment by vickystickz** [comment]
> Contributing needs more information , For eg : There should be steps about understanding the license , navigating to readme , follow the ethical guidelines , coding standards , proper branching name and PR methods ! We can work on it future , Merging this PR for now to start with

Alright noted

**Comment by petya-kangalova** [comment]
@kshitijrajsharma  100%, did we have to wait for all remaining open PRs to be approved (that had that additional content) before merging? I thought they can be merged 1 by 1 and then have thee complete contributor guidance.

**Pull request merged**
