### PR TITLE
Updated Readme.md

### PR DESCRIPTION
**Pull request by neelimagoogly**
I have added the diagrams of General Workflow of fAIr and fAIr architecture to the README file wrt #128.   @kshitijrajsharma , @omranlm and @petya-kangalova please review it.

### CODE REVIEW

**Comment by omranlm** [comment]
I would recommend adding narrative explanations for the diagrams. They feel (my point of view) bare and the idea behind is not so clear .. However, @kshitijrajsharma and myself should do as we talked about it before. I would suggest you @neelimagoogly  try to put a narrative description based on your understanding as a core text. Then I can edit with Kshitij and close the PR
Thank

**Comment by neelimagoogly** [comment]
> 

Done .

**Comment by neelimagoogly** [comment]
> I would recommend adding narrative explanations for the diagrams. They feel (my point of view) bare and the idea behind is not so clear .. However, @kshitijrajsharma and myself should do as we talked about it before. I would suggest you @neelimagoogly try to put a narrative description based on your understanding as a core text. Then I can edit with Kshitij and close the PR Thank

Done.

**Comment by kshitijrajsharma** [comment]
@neelimagoogly 
Few tips for Raising PR :
- Provide a Meaningful Title & Summary description which narrates the changes you did on PR 
- Request review from Reviewers tab located on right side of the PR Screen
- Convert PR to Draft when you are working on it

**Comment by neelimagoogly** [comment]
> @neelimagoogly Few tips for Raising PR :
> 
> * Provide a Meaningful Title & Summary description which narrates the changes you did on PR
> * Request review from Reviewers tab located on right side of the PR Screen
> * Convert PR to Draft when you are working on it

Thanks @kshitijrajsharma , I will keep this in mind while creating PRs everytime.

**Review by kshitijrajsharma — CHANGES_REQUESTED** [review]
Better to use relative path like this (./docs) instead of full links 
In this way user working on any branch can have access to this relatively 
This needs to be changed where files are referenced in all over the PR except external links

**Review by kshitijrajsharma — APPROVED** [review]

**Pull request merged**
