### PR TITLE
Update Docker-installation.md

### LINKED ISSUE #235: Typo in Docker Installation Guide
The documentation for the Docker installation guide (https://github.com/hotosm/fAIr/blob/master/docs/Docker-installation.md) contains a typo in the section regarding cloning the repository. The word "Clonse" is used instead of "clone." This typo could potentially cause confusion for users following the installation instructions. Let's correct this typo to ensure the accuracy and clarity of the documentation.

### PR DESCRIPTION
**Pull request by nwekealex65**
--- What does this PR do ?
Fixed Typo in https://github.com/hotosm/fAIr/blob/master/docs/Docker-installation.md and enhanced the section for creating .env files

- Resolve #235

### CODE REVIEW

**Comment by Ettrig** [comment]
This commit changes the numbers given to the steps, so that no step has number 7.  In this respect it does not seem to be an improvement.

**Comment by nwekealex65** [comment]
So the numbers given to the steps are preserved. A typo `Clonse` changed to `Clone`

**Comment by nwekealex65** [comment]
> This commit changes the numbers given to the steps, so that no step has number 7. In this respect it does not seem to be an improvement.

@Ettrig I have fixed the numbering, review

**Review by kshitijrajsharma — APPROVED** [review]

**Comment by kshitijrajsharma** [comment]
Thanks for the PR

**Pull request merged**
