### PR TITLE
Feature : Background Task Processing  , Authentication , Documentation enhancement and many more 

### LINKED ISSUE #24: Integrate oauth osm 2.0 to django user model
plan is to integrate osm user with native django user with osm_id as unique value

### LINKED ISSUE #25: Implement Training and Model with their CURD API

### LINKED ISSUE #26: Setup Backend with Queue system

### LINKED ISSUE #27: Enable queue and tasks when training is created or add methods to run it

### PR DESCRIPTION
**Pull request by kshitijrajsharma**
- Resolve #24  Adds authentication on endpoints 
Now authentication is compulsory on most of the endpoints , if user is not authorized you will be denied to perform operation , and also ```created_by``` field is replaced with the actual user who is registered to do operation ( previously it was int for osm_id , now it is user itself who is authenticated ) 
- Swagger is now configured with osm authentication 
image
You can pass your access token and use across all the endpoints from swagger 

- Now ulitites functions for the API has been moved to ```utils.py``` so that ```views.py``` holds logic for API only 

- Introduces new ```task.py``` that can be used to define the logic that are needed to perform using queue system ! Celery is configured and binded to the App itself so celery will always be configured when app starts , it is not possible to start app without celery 

- Resolve #25   Introduces two new curd operations : Training & Model 
image

- Resolve #26  Introduces background processing using celery 
image

- Upgrades swagger and available in ```/swagger``` also redoc in ```/redoc``` migrated from homepage 
image

- Resolve #27   Introduces two new endpoint to keep track of training going on and train model , Demo method for now 
image

**What Next ?  :** 

- #29  

**Test :** 
- You will need redis installed on your system , Follow ```backend build ``` to get idea 
- You need celery configured with redis , API is capable of storing result to both options : redis / django db itself , You can change the env variable to configure 
- You need to launch the worker , flower and API at three different terminals and get all of them running in order to execute whole workflow as defined. in instructions ```readme```

**Workflow :** 

image

### CODE REVIEW

**Review by omranlm — APPROVED** [review]
Looks great

**Comment by omranlm** [comment]
> Looks great

waiting the agreed changes ..

**Comment by kshitijrajsharma** [comment]
Things to do before making this PR Ready : 

- [x] add epoch and batch size in training

- [x]  send directly to the queue

- [x] model meta data about the published training

**Comment by kshitijrajsharma** [comment]
**Crucial Update on API endpoints :** 
This will break the UI 

- ```/dataset_image/build/** ``` has been migrated to ```/dataset/image/build/```  to maintain consistency with dataset endpoint , similarly ```/fetch-raw/``` also migrated to ```/label/osm/fetch/```  
cc : @omranlm 

**Tested :**  
Workflow tested form creation of dataset - to creation of training while placing task to queue  
1) Creation of Dataset 
2) Create of AOI under dataset 
3) Download Osm data as labels inside AOI 
4) Build dataset by downloading image and lables.geojson 
5) Creation of Model 
6) Creation of training : Training creation triggered task to go to queue

**Comment by omranlm** [comment]
Great @kshitijrajsharma  ready to merge ?

**Comment by kshitijrajsharma** [comment]
From my end , Yes 🙌!

**Pull request merged**
